---
title: "Useful references and tutorials on using bash"
author: "Tonya Severson"
date: "`r Sys.Date()`"
output: md_document
---


Below are a few selected resources (tutorials, documentation, books) that I've found valuable for figuring out how to do things on the command line in the bash shell.

## Tutorials

### WestDRI
Alex Razoumov and Marie Helene Burle are awesome and are based at SFU. They present training sessions on a variety of topics. Training materials and schedule are available [here](https://training.westdri.ca/)

### software carpentry

A gentle introduction to working on the command line in the Unix shell. <https://swcarpentry.github.io/shell-novice/index.html>

### W3 schools

<https://www.w3schools.com/bash/>

Great reference and introduction to basic commands, working with text, and writing scripts. (Also has extensive material for other programming languages.) 


## Documentation

* [Alliance Canada](https://docs.alliancecan.ca/wiki/Linux_introduction)

## Books

### *O'Reilly for Higher Education*

[UBC Library]<https://resources.library.ubc.ca/page.php?id=2460> provides access to *O'Reilly for Higher Education* to UBC affiliates, which is a terrific resource for learning about all things related to programming. Many of the books were originally published by *O'Reilly Media, Inc.*, but it also includes access to videos, and titles from other publishers like Manning Publications.

Books available that I've found particularly useful include:

* [Learning the bash Shell]<https://learning.oreilly.com/library/view/learning-the-bash/0596009658/>

* [sed & awk]<https://learning.oreilly.com/library/view/sed-awk/1565922255/>

* [Unix in a Nutshell]<https://learning.oreilly.com/library/view/unix-in-a/0596100299/>

However, many other books are available on bash and many other programming languages in O'Reilly's extensive database.







